#!/usr/bin/env node
/**
 * digest-renderer — turn a markdown source into a paired (desktop + mobile)
 * HTML output. Standalone CLI version of the session-digest capability's
 * render step; useful for one-off conversions without spinning up the cap.
 *
 * Run:
 *   node tools/digest-renderer/render.mjs --in input.md --out-dir out/
 *   node tools/digest-renderer/render.mjs --in input.md --brand impactiq
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, basename, extname } from 'node:path';

const args = process.argv.slice(2);
const opts = { brand: 'ward-tech-systems' };
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === '--in') opts.input = args[++i];
  else if (a === '--out-dir') opts.outDir = args[++i];
  else if (a === '--brand') opts.brand = args[++i];
}
if (!opts.input) {
  console.error('usage: --in <input.md> [--out-dir <dir>] [--brand ward-tech-systems|impactiq|onlyjalen|generic]');
  process.exit(2);
}

const BRANDS = {
  'ward-tech-systems': { accent: '#A0752C', bg: '#000', fg: '#F4F1ED' },
  'impactiq':          { accent: '#DEB568', bg: '#000', fg: '#F4F1ED' },
  'onlyjalen':         { accent: '#FF4D4F', bg: '#0A0A0A', fg: '#FFFFFF' },
  'generic':           { accent: '#3B82F6', bg: '#FFFFFF', fg: '#111827' },
};
const brand = BRANDS[opts.brand] ?? BRANDS.generic;

const src = await readFile(resolve(opts.input), 'utf8');
const title = src.match(/^#\s+(.+)$/m)?.[1] ?? basename(opts.input, extname(opts.input));

// Minimal markdown → HTML — no marked dep needed for the basics.
function md2html(md) {
  let html = md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.+<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n\n+/g, '</p><p>');
  return `<p>${html}</p>`.replace(/<p>(<h\d|<ul)/g, '$1').replace(/(<\/h\d>|<\/ul>)<\/p>/g, '$1');
}

const bodyHtml = md2html(src);

const desktopHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"/><title>${title}</title>
<style>
@page{size:A4;margin:18mm}
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:${brand.bg};color:${brand.fg};line-height:1.6;padding:40px 60px}
h1,h2,h3{color:${brand.accent};border-bottom:1px solid ${brand.accent}44;padding-bottom:8px}
h1{font-size:32px}h2{font-size:22px;margin-top:32px}
code{background:rgba(255,255,255,.06);padding:2px 6px;border-radius:3px;font-family:'JetBrains Mono',Consolas,monospace}
ul{padding-left:24px}li{margin:6px 0}
strong{color:${brand.accent}}
footer{margin-top:60px;padding-top:16px;border-top:1px solid ${brand.accent}44;color:${brand.fg}77;font-size:12px}
</style></head><body>${bodyHtml}<footer>Generated by tools/digest-renderer · ${new Date().toISOString()} · brand:${opts.brand}</footer></body></html>`;

// Email-safe inline-CSS variant (no media queries, table layout).
const mobileHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/><title>${title}</title></head>
<body style="margin:0;padding:0;background:${brand.bg};font-family:Arial,sans-serif">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:${brand.bg}">
<tr><td align="center" style="padding:20px 0">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;background:${brand.bg};color:${brand.fg}">
<tr><td style="padding:24px;color:${brand.fg};line-height:1.55;font-size:15px">${bodyHtml.replace(/<h1>/g, `<h1 style="color:${brand.accent};font-size:24px;margin:0 0 12px">`).replace(/<h2>/g, `<h2 style="color:${brand.accent};font-size:18px;margin:24px 0 8px">`).replace(/<code>/g, `<code style="background:rgba(255,255,255,.08);padding:2px 5px;font-family:Consolas,monospace">`).replace(/<strong>/g, `<strong style="color:${brand.accent}">`)}</td></tr>
<tr><td style="padding:16px 24px;color:${brand.fg}77;font-size:12px;border-top:1px solid ${brand.accent}33">Generated ${new Date().toISOString().slice(0,10)} · ${opts.brand}</td></tr>
</table></td></tr></table></body></html>`;

const outDir = opts.outDir ? resolve(opts.outDir) : resolve('.');
await mkdir(outDir, { recursive: true });
const stem = basename(opts.input, extname(opts.input));
await writeFile(`${outDir}/${stem}.desktop.html`, desktopHtml, 'utf8');
await writeFile(`${outDir}/${stem}.mobile.html`, mobileHtml, 'utf8');

console.log(`${outDir}/${stem}.desktop.html`);
console.log(`${outDir}/${stem}.mobile.html`);
